# Generated by Django 6.0.6 on 2026-06-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_contactenquiry_delete_contact_delete_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='contactenquiry',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
